//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.App.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevManager.App.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DevManager.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to calisyor.
        /// </summary>
        public static string App_Running {
            get {
                return ResourceManager.GetString("App_Running", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tumunu Baslat.
        /// </summary>
        public static string Menu_StartAll {
            get {
                return ResourceManager.GetString("Menu_StartAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tumunu Durdur.
        /// </summary>
        public static string Menu_StopAll {
            get {
                return ResourceManager.GetString("Menu_StopAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hakkinda.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PROJELER.
        /// </summary>
        public static string Projects_Header {
            get {
                return ResourceManager.GetString("Projects_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + Proje Ekle.
        /// </summary>
        public static string Projects_AddProject {
            get {
                return ResourceManager.GetString("Projects_AddProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bir proje secin veya yeni proje ekleyin.
        /// </summary>
        public static string Projects_SelectPrompt {
            get {
                return ResourceManager.GetString("Projects_SelectPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tum surecleri baslat.
        /// </summary>
        public static string Project_StartAll {
            get {
                return ResourceManager.GetString("Project_StartAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tum surecleri durdur.
        /// </summary>
        public static string Project_StopAll {
            get {
                return ResourceManager.GetString("Project_StopAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tum surecleri yeniden baslat.
        /// </summary>
        public static string Project_RestartAll {
            get {
                return ResourceManager.GetString("Project_RestartAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Surec Ekle.
        /// </summary>
        public static string Project_AddProcess {
            get {
                return ResourceManager.GetString("Project_AddProcess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Projeyi Sil.
        /// </summary>
        public static string Project_Delete {
            get {
                return ResourceManager.GetString("Project_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; projesini silmek istediginize emin misiniz?.
        /// </summary>
        public static string Project_DeleteConfirm {
            get {
                return ResourceManager.GetString("Project_DeleteConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Proje Sil.
        /// </summary>
        public static string Project_DeleteTitle {
            get {
                return ResourceManager.GetString("Project_DeleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Baslat.
        /// </summary>
        public static string Process_Start {
            get {
                return ResourceManager.GetString("Process_Start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Durdur.
        /// </summary>
        public static string Process_Stop {
            get {
                return ResourceManager.GetString("Process_Stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yeniden Baslat.
        /// </summary>
        public static string Process_Restart {
            get {
                return ResourceManager.GetString("Process_Restart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loglari Temizle.
        /// </summary>
        public static string Process_ClearLogs {
            get {
                return ResourceManager.GetString("Process_ClearLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loglari Kopyala.
        /// </summary>
        public static string Process_CopyLogs {
            get {
                return ResourceManager.GetString("Process_CopyLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sureci Sil.
        /// </summary>
        public static string Process_Delete {
            get {
                return ResourceManager.GetString("Process_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; surecini silmek istediginize emin misiniz?.
        /// </summary>
        public static string Process_DeleteConfirm {
            get {
                return ResourceManager.GetString("Process_DeleteConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Surec Sil.
        /// </summary>
        public static string Process_DeleteTitle {
            get {
                return ResourceManager.GetString("Process_DeleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yeniden baslatma sayisi:.
        /// </summary>
        public static string Process_RestartCount {
            get {
                return ResourceManager.GetString("Process_RestartCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calisiyor.
        /// </summary>
        public static string State_Running {
            get {
                return ResourceManager.GetString("State_Running", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Durduruldu.
        /// </summary>
        public static string State_Stopped {
            get {
                return ResourceManager.GetString("State_Stopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Baslatiliyor....
        /// </summary>
        public static string State_Starting {
            get {
                return ResourceManager.GetString("State_Starting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Durduruluyor....
        /// </summary>
        public static string State_Stopping {
            get {
                return ResourceManager.GetString("State_Stopping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Coktu.
        /// </summary>
        public static string State_Crashed {
            get {
                return ResourceManager.GetString("State_Crashed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yeniden Baslatiliyor....
        /// </summary>
        public static string State_Restarting {
            get {
                return ResourceManager.GetString("State_Restarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bilinmiyor.
        /// </summary>
        public static string State_Unknown {
            get {
                return ResourceManager.GetString("State_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yeni Proje Ekle.
        /// </summary>
        public static string Dialog_AddProject_Title {
            get {
                return ResourceManager.GetString("Dialog_AddProject_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yeni Proje.
        /// </summary>
        public static string Dialog_AddProject_Header {
            get {
                return ResourceManager.GetString("Dialog_AddProject_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_PathHint.
        /// </summary>
        public static string Dialog_AddProject_PathHint {
            get {
                return ResourceManager.GetString("Dialog_AddProject_PathHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_BrowseFolder.
        /// </summary>
        public static string Dialog_AddProject_BrowseFolder {
            get {
                return ResourceManager.GetString("Dialog_AddProject_BrowseFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_Scan.
        /// </summary>
        public static string Dialog_AddProject_Scan {
            get {
                return ResourceManager.GetString("Dialog_AddProject_Scan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_ScanTooltip.
        /// </summary>
        public static string Dialog_AddProject_ScanTooltip {
            get {
                return ResourceManager.GetString("Dialog_AddProject_ScanTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_NameHint.
        /// </summary>
        public static string Dialog_AddProject_NameHint {
            get {
                return ResourceManager.GetString("Dialog_AddProject_NameHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_Color.
        /// </summary>
        public static string Dialog_AddProject_Color {
            get {
                return ResourceManager.GetString("Dialog_AddProject_Color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_AutoStart.
        /// </summary>
        public static string Dialog_AddProject_AutoStart {
            get {
                return ResourceManager.GetString("Dialog_AddProject_AutoStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_ScanPrompt.
        /// </summary>
        public static string Dialog_AddProject_ScanPrompt {
            get {
                return ResourceManager.GetString("Dialog_AddProject_ScanPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_NoResults.
        /// </summary>
        public static string Dialog_AddProject_NoResults {
            get {
                return ResourceManager.GetString("Dialog_AddProject_NoResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_ResultCount.
        /// </summary>
        public static string Dialog_AddProject_ResultCount {
            get {
                return ResourceManager.GetString("Dialog_AddProject_ResultCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_Cancel.
        /// </summary>
        public static string Dialog_AddProject_Cancel {
            get {
                return ResourceManager.GetString("Dialog_AddProject_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_Add.
        /// </summary>
        public static string Dialog_AddProject_Add {
            get {
                return ResourceManager.GetString("Dialog_AddProject_Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_NameRequired.
        /// </summary>
        public static string Dialog_AddProject_NameRequired {
            get {
                return ResourceManager.GetString("Dialog_AddProject_NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_PathRequired.
        /// </summary>
        public static string Dialog_AddProject_PathRequired {
            get {
                return ResourceManager.GetString("Dialog_AddProject_PathRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProject_PathNotFound.
        /// </summary>
        public static string Dialog_AddProject_PathNotFound {
            get {
                return ResourceManager.GetString("Dialog_AddProject_PathNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_Title.
        /// </summary>
        public static string Dialog_AddProcess_Title {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_Header.
        /// </summary>
        public static string Dialog_AddProcess_Header {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_NameHint.
        /// </summary>
        public static string Dialog_AddProcess_NameHint {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_NameHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_CommandHint.
        /// </summary>
        public static string Dialog_AddProcess_CommandHint {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_CommandHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_ArgsHint.
        /// </summary>
        public static string Dialog_AddProcess_ArgsHint {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_ArgsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_WorkDirHint.
        /// </summary>
        public static string Dialog_AddProcess_WorkDirHint {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_WorkDirHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_EnvVars.
        /// </summary>
        public static string Dialog_AddProcess_EnvVars {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_EnvVars", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_AutoRestart.
        /// </summary>
        public static string Dialog_AddProcess_AutoRestart {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_AutoRestart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_MaxRetries.
        /// </summary>
        public static string Dialog_AddProcess_MaxRetries {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_MaxRetries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_Delay.
        /// </summary>
        public static string Dialog_AddProcess_Delay {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_Delay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_StartupDelay.
        /// </summary>
        public static string Dialog_AddProcess_StartupDelay {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_StartupDelay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_AutoStartWithProject.
        /// </summary>
        public static string Dialog_AddProcess_AutoStartWithProject {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_AutoStartWithProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_Cancel.
        /// </summary>
        public static string Dialog_AddProcess_Cancel {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_Add.
        /// </summary>
        public static string Dialog_AddProcess_Add {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_NameRequired.
        /// </summary>
        public static string Dialog_AddProcess_NameRequired {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_CommandRequired.
        /// </summary>
        public static string Dialog_AddProcess_CommandRequired {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_CommandRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_BrowseCommand.
        /// </summary>
        public static string Dialog_AddProcess_BrowseCommand {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_BrowseCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_BrowseWorkDir.
        /// </summary>
        public static string Dialog_AddProcess_BrowseWorkDir {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_BrowseWorkDir", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog_AddProcess_FileFilter.
        /// </summary>
        public static string Dialog_AddProcess_FileFilter {
            get {
                return ResourceManager.GetString("Dialog_AddProcess_FileFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About_Title.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About_AppName.
        /// </summary>
        public static string About_AppName {
            get {
                return ResourceManager.GetString("About_AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About_Description.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About_Company.
        /// </summary>
        public static string About_Company {
            get {
                return ResourceManager.GetString("About_Company", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About_Close.
        /// </summary>
        public static string About_Close {
            get {
                return ResourceManager.GetString("About_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color_Blue.
        /// </summary>
        public static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color_Red.
        /// </summary>
        public static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color_Green.
        /// </summary>
        public static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color_Orange.
        /// </summary>
        public static string Color_Orange {
            get {
                return ResourceManager.GetString("Color_Orange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color_Purple.
        /// </summary>
        public static string Color_Purple {
            get {
                return ResourceManager.GetString("Color_Purple", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color_Teal.
        /// </summary>
        public static string Color_Teal {
            get {
                return ResourceManager.GetString("Color_Teal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color_Pink.
        /// </summary>
        public static string Color_Pink {
            get {
                return ResourceManager.GetString("Color_Pink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color_Indigo.
        /// </summary>
        public static string Color_Indigo {
            get {
                return ResourceManager.GetString("Color_Indigo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning_Title.
        /// </summary>
        public static string Warning_Title {
            get {
                return ResourceManager.GetString("Warning_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error_Title.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error_AppError.
        /// </summary>
        public static string Error_AppError {
            get {
                return ResourceManager.GetString("Error_AppError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error_AppErrorTitle.
        /// </summary>
        public static string Error_AppErrorTitle {
            get {
                return ResourceManager.GetString("Error_AppErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error_LoadFailed.
        /// </summary>
        public static string Error_LoadFailed {
            get {
                return ResourceManager.GetString("Error_LoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log_OrphanAdopted.
        /// </summary>
        public static string Log_OrphanAdopted {
            get {
                return ResourceManager.GetString("Log_OrphanAdopted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_Starting.
        /// </summary>
        public static string Process_Starting {
            get {
                return ResourceManager.GetString("Process_Starting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_Started.
        /// </summary>
        public static string Process_Started {
            get {
                return ResourceManager.GetString("Process_Started", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_Stopping (log message).
        /// </summary>
        public static string Process_Stopping {
            get {
                return ResourceManager.GetString("Process_Stopping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_Stopped (log message).
        /// </summary>
        public static string Process_Stopped {
            get {
                return ResourceManager.GetString("Process_Stopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_FailedToStart.
        /// </summary>
        public static string Process_FailedToStart {
            get {
                return ResourceManager.GetString("Process_FailedToStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_ExitedNormally.
        /// </summary>
        public static string Process_ExitedNormally {
            get {
                return ResourceManager.GetString("Process_ExitedNormally", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_ExitedWithCode.
        /// </summary>
        public static string Process_ExitedWithCode {
            get {
                return ResourceManager.GetString("Process_ExitedWithCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_AutoRestarting.
        /// </summary>
        public static string Process_AutoRestarting {
            get {
                return ResourceManager.GetString("Process_AutoRestarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_MaxRestartsReached.
        /// </summary>
        public static string Process_MaxRestartsReached {
            get {
                return ResourceManager.GetString("Process_MaxRestartsReached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_OrphanDetected.
        /// </summary>
        public static string Process_OrphanDetected {
            get {
                return ResourceManager.GetString("Process_OrphanDetected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process_OrphanLogNote.
        /// </summary>
        public static string Process_OrphanLogNote {
            get {
                return ResourceManager.GetString("Process_OrphanLogNote", resourceCulture);
            }
        }
    }
}
